-- MySQL Script generated by MySQL Workbench
-- 03/05/15 19:31:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbteste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbteste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbteste` DEFAULT CHARACTER SET utf8 ;
USE `dbteste` ;

-- -----------------------------------------------------
-- Table `dbteste`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`clientes` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `nome` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sobrenome` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `dbteste`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbteste`.`pedidos` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `status` enum('new','pending','delivered') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'new',
  `id_cliente` bigint(20) unsigned NOT NULL,
  `valor` double(8,2) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pedidos_id_cliente_foreign` (`id_cliente`),
  CONSTRAINT `pedidos_id_cliente_foreign` FOREIGN KEY (`id_cliente`) REFERENCES `clientes` (`id`)
) ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;